apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  source:
    chart: grafana
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.59.4
    helm:
      values: |
        adminPassword: admin
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
            - name: Prometheus
              type: prometheus
              url: http://prometheus-server:80
              access: proxy
              isDefault: true
            - name: Tempo
              type: tempo
              url: http://tempo:3100
              access: proxy
            - name: Pyroscope
              type: grafana-pyroscope-datasource
              url: http://pyroscope:4040
              access: proxy
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
