apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

# Sẽ được đè lại bởi CI/CD Github Actions hoặc kustomize config tại overlays
images:
  - name: go-observability-playground
    newName: ghcr.io/huyhihi1/go-observability-playground
    newTag: latest
