global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'server-a'
    static_configs:
      - targets: ['server-a:8080']
  - job_name: 'server-b'
    static_configs:
      - targets: ['server-b:8081']
